import { env, SELF } from "cloudflare:test";
import { beforeEach, describe, expect, it } from "vitest";

import { COMMUNITY_LIMITS } from "../shared/community";
import { sha256 } from "./crypto";

const ORIGIN = "http://localhost:3000";
const SESSION_PEPPER = "test-only-session-pepper";
const HOUR_MS = 60 * 60 * 1_000;
const DAY_MS = 24 * HOUR_MS;

describe("database-authoritative quota admission", () => {
  beforeEach(async () => {
    await clearR2();
    await env.DB.exec(`
      DELETE FROM quota_reservations;
      DELETE FROM moderation_actions;
      DELETE FROM reports;
      DELETE FROM follows;
      DELETE FROM comments;
      DELETE FROM likes;
      DELETE FROM creation_search;
      DELETE FROM creation_tags;
      DELETE FROM creation_objects;
      DELETE FROM creation_revisions;
      DELETE FROM creation_stats;
      DELETE FROM creations;
      DELETE FROM sessions;
      DELETE FROM external_identities;
      DELETE FROM users;
    `);
  });

  it("admits only one of two concurrent creations at the 100-creation boundary", async () => {
    const owner = await seedUser("creation-owner");
    const token = await seedSession(owner.id, "creation-owner-token");
    const now = Date.now();
    await env.DB.prepare(
      `WITH RECURSIVE sequence(value) AS (
         SELECT 1
         UNION ALL
         SELECT value + 1 FROM sequence WHERE value < 99
       )
       INSERT INTO creations
       (id, owner_user_id, slug, title, description, state, visibility,
        comments_enabled, project_download_enabled, bytes_total, created_at, updated_at)
       SELECT 'seed-creation-' || printf('%03d', value), ?,
         'seed-' || printf('%013d', value), 'Seed ' || value, '', 'draft', 'private',
         0, 0, 0, ?, ? FROM sequence`,
    )
      .bind(owner.id, now, now)
      .run();

    const responses = await Promise.all([
      createCloudProject(token, "Boundary project A"),
      createCloudProject(token, "Boundary project B"),
    ]);

    expect(responses.map((response) => response.status).sort()).toEqual([
      201, 409,
    ]);
    const rejected = responses.find((response) => response.status === 409)!;
    await expect(rejected.json()).resolves.toMatchObject({
      error: { code: "QUOTA_EXCEEDED" },
    });
    await expect(
      env.DB.prepare(
        "SELECT COUNT(*) AS count FROM creations WHERE owner_user_id = ?",
      )
        .bind(owner.id)
        .first(),
    ).resolves.toMatchObject({ count: 100 });
    await expect(activeReservationTotal(owner.id)).resolves.toMatchObject({
      count: 0,
      storage_bytes: 0,
    });
  });

  it("atomically reserves storage across concurrent distinct revisions", async () => {
    const owner = await seedUser("storage-racer");
    const first = await seedUploadingRevision(owner.id, "Storage race A");
    const second = await seedUploadingRevision(owner.id, "Storage race B");
    const now = Date.now();
    await env.DB.batch([
      reservationStatement(first.revisionId, owner.id, now),
      reservationStatement(second.revisionId, owner.id, now),
    ]);

    const bytes = 30 * 1024 * 1024;
    const results = await Promise.allSettled([
      reserveBytes(first.revisionId, bytes),
      reserveBytes(second.revisionId, bytes),
    ]);

    expect(
      results.filter((result) => result.status === "fulfilled"),
    ).toHaveLength(1);
    expect(
      results.filter((result) => result.status === "rejected"),
    ).toHaveLength(1);
    const rejected = results.find((result) => result.status === "rejected");
    expect(rejected).toMatchObject({
      reason: expect.objectContaining({
        message: expect.stringMatching(/storage_quota_exceeded/iu),
      }),
    });
    await expect(activeReservationTotal(owner.id)).resolves.toMatchObject({
      count: 2,
      storage_bytes: bytes,
    });
  });

  it("releases R2 and D1 state when exact generated bytes exceed storage quota", async () => {
    const owner = await seedUser("storage-owner");
    const token = await seedSession(owner.id, "storage-owner-token");
    await seedCommittedStorage(
      owner.id,
      COMMUNITY_LIMITS.cloudBytesPerUser - 1,
    );

    const response = await createCloudProject(token, "Over quota project");

    expect(response.status).toBe(409);
    await expect(response.json()).resolves.toMatchObject({
      error: { code: "QUOTA_EXCEEDED" },
    });
    await expect(
      env.DB.prepare(
        "SELECT COUNT(*) AS count FROM creations WHERE owner_user_id = ?",
      )
        .bind(owner.id)
        .first(),
    ).resolves.toMatchObject({ count: 1 });
    await expect(activeReservationTotal(owner.id)).resolves.toMatchObject({
      count: 0,
      storage_bytes: 0,
    });
    expect((await env.PROJECTS.list()).objects).toHaveLength(0);
  });

  it("releases stale reservations when scheduled cleanup marks an upload failed", async () => {
    const owner = await seedUser("stale-owner");
    const upload = await seedUploadingRevision(owner.id, "Stale upload");
    const now = Date.now();
    await env.DB.batch([
      reservationStatement(upload.revisionId, owner.id, now),
      env.DB.prepare(
        "UPDATE quota_reservations SET storage_bytes = ? WHERE id = ?",
      ).bind(30 * 1024 * 1024, upload.revisionId),
    ]);

    await env.DB.prepare(
      "UPDATE creation_revisions SET status = 'failed' WHERE id = ? AND status = 'uploading'",
    )
      .bind(upload.revisionId)
      .run();

    expect(
      await env.DB.prepare(
        "SELECT 1 AS found FROM quota_reservations WHERE id = ?",
      )
        .bind(upload.revisionId)
        .first(),
    ).toBeNull();
  });
});

describe("database-authoritative rolling report limit", () => {
  beforeEach(async () => {
    await env.DB.exec(`
      DELETE FROM quota_reservations;
      DELETE FROM moderation_actions;
      DELETE FROM reports;
      DELETE FROM follows;
      DELETE FROM comments;
      DELETE FROM likes;
      DELETE FROM creation_search;
      DELETE FROM creation_tags;
      DELETE FROM creation_objects;
      DELETE FROM creation_revisions;
      DELETE FROM creation_stats;
      DELETE FROM creations;
      DELETE FROM sessions;
      DELETE FROM external_identities;
      DELETE FROM users;
    `);
  });

  it("admits exactly five of six concurrent reports against distinct targets", async () => {
    const reporter = await seedUser("reporter-one");
    const token = await seedSession(reporter.id, "reporter-one-token");
    const targets = await Promise.all(
      Array.from({ length: 6 }, (_, index) => seedUser(`target-${index + 1}`)),
    );

    const responses = await Promise.all(
      targets.map((target) => createReport(token, target.id)),
    );

    expect(responses.map((response) => response.status).sort()).toEqual([
      201, 201, 201, 201, 201, 429,
    ]);
    expect(
      responses
        .find((response) => response.status === 429)
        ?.headers.get("retry-after"),
    ).toBe("86400");
    await expect(
      env.DB.prepare(
        "SELECT COUNT(*) AS count FROM reports WHERE reporter_user_id = ?",
      )
        .bind(reporter.id)
        .first(),
    ).resolves.toMatchObject({ count: 5 });
  });

  it("preserves duplicate-open-report uniqueness", async () => {
    const reporter = await seedUser("reporter-two");
    const target = await seedUser("duplicate-target");
    const token = await seedSession(reporter.id, "reporter-two-token");

    expect((await createReport(token, target.id)).status).toBe(201);
    const duplicate = await createReport(token, target.id);

    expect(duplicate.status).toBe(409);
    await expect(duplicate.json()).resolves.toMatchObject({
      error: { code: "CONFLICT" },
    });
  });

  it("does not count reports older than the rolling 24-hour window", async () => {
    const reporter = await seedUser("reporter-three");
    const token = await seedSession(reporter.id, "reporter-three-token");
    const targets = await Promise.all(
      Array.from({ length: 6 }, (_, index) =>
        seedUser(`old-target-${index + 1}`),
      ),
    );
    const oldTimestamp = Date.now() - DAY_MS - 1_000;
    for (const target of targets.slice(0, 5)) {
      await insertReport(reporter.id, target.id, oldTimestamp);
    }

    expect((await createReport(token, targets[5].id)).status).toBe(201);
  });
});

async function createCloudProject(
  token: string,
  name: string,
): Promise<Response> {
  return SELF.fetch(`${ORIGIN}/api/creations`, {
    body: JSON.stringify({ project: project(name), title: name }),
    headers: authenticatedHeaders(token),
    method: "POST",
  });
}

async function createReport(
  token: string,
  targetId: string,
): Promise<Response> {
  return SELF.fetch(`${ORIGIN}/api/reports`, {
    body: JSON.stringify({
      details: "Focused concurrency test",
      reason: "spam",
      targetId,
      targetType: "user",
    }),
    headers: authenticatedHeaders(token),
    method: "POST",
  });
}

async function seedUser(username: string): Promise<{ id: string }> {
  const id = crypto.randomUUID();
  const now = Date.now();
  await env.DB.batch([
    env.DB.prepare(
      `INSERT INTO users
       (id, username, display_name, bio, role, status, avatar_seed,
        terms_version, terms_accepted_at, created_at, updated_at)
       VALUES (?, ?, ?, '', 'user', 'active', ?, '2026-07-12', ?, ?, ?)`,
    ).bind(id, username, username, id, now, now, now),
    env.DB.prepare(
      `INSERT INTO external_identities
       (id, user_id, provider, provider_subject, email, email_verified, created_at, updated_at)
       VALUES (?, ?, 'google', ?, ?, 1, ?, ?)`,
    ).bind(
      crypto.randomUUID(),
      id,
      `subject-${id}`,
      `${username}@example.test`,
      now,
      now,
    ),
  ]);
  return { id };
}

async function seedSession(userId: string, token: string): Promise<string> {
  const now = Date.now();
  await env.DB.prepare(
    `INSERT INTO sessions
     (id, token_hash, user_id, ua_label, created_at, last_seen_at,
      last_authenticated_at, expires_at)
     VALUES (?, ?, ?, 'Quota test browser', ?, ?, ?, ?)`,
  )
    .bind(
      crypto.randomUUID(),
      await sha256(`${SESSION_PEPPER}:${token}`),
      userId,
      now,
      now,
      now,
      now + HOUR_MS,
    )
    .run();
  return token;
}

async function seedUploadingRevision(
  userId: string,
  title: string,
): Promise<{ creationId: string; revisionId: string }> {
  const creationId = crypto.randomUUID();
  const revisionId = crypto.randomUUID();
  const now = Date.now();
  await env.DB.batch([
    env.DB.prepare(
      `INSERT INTO creations
       (id, owner_user_id, slug, title, description, state, visibility,
        comments_enabled, project_download_enabled, bytes_total, created_at, updated_at)
       VALUES (?, ?, ?, ?, '', 'draft', 'private', 0, 0, 0, ?, ?)`,
    ).bind(creationId, userId, randomSlug(), title, now, now),
    env.DB.prepare(
      `INSERT INTO creation_revisions
       (id, creation_id, revision_number, status, project_bytes, created_at)
       VALUES (?, ?, 1, 'uploading', 1, ?)`,
    ).bind(revisionId, creationId, now),
    env.DB.prepare(
      `INSERT INTO creation_stats
       (creation_id, like_count, comment_count, popularity_score, updated_at)
       VALUES (?, 0, 0, 0, ?)`,
    ).bind(creationId, now),
  ]);
  return { creationId, revisionId };
}

async function seedCommittedStorage(
  userId: string,
  bytes: number,
): Promise<void> {
  const { creationId, revisionId } = await seedUploadingRevision(
    userId,
    "Existing storage",
  );
  const now = Date.now();
  await env.DB.batch([
    env.DB.prepare(
      `UPDATE creation_revisions
       SET status = 'ready', project_sha256 = ?, ready_at = ? WHERE id = ?`,
    ).bind("0".repeat(64), now, revisionId),
    env.DB.prepare(
      "UPDATE creations SET current_revision_id = ?, bytes_total = ? WHERE id = ?",
    ).bind(revisionId, bytes, creationId),
    env.DB.prepare(
      `INSERT INTO creation_objects
       (id, creation_id, revision_id, kind, object_key, content_type,
        byte_size, sha256, status, created_at, updated_at)
       VALUES (?, ?, ?, 'project_json', ?, 'application/json', ?, ?, 'ready', ?, ?)`,
    ).bind(
      crypto.randomUUID(),
      creationId,
      revisionId,
      `private/creations/${creationId}/${revisionId}/project.json`,
      bytes,
      "1".repeat(64),
      now,
      now,
    ),
  ]);
}

function reservationStatement(
  id: string,
  userId: string,
  now: number,
): D1PreparedStatement {
  return env.DB.prepare(
    `INSERT INTO quota_reservations
     (id, user_id, creation_slots, storage_bytes, created_at, updated_at, expires_at)
     VALUES (?, ?, 0, 0, ?, ?, ?)`,
  ).bind(id, userId, now, now, now + HOUR_MS);
}

function reserveBytes(id: string, bytes: number): Promise<D1Result> {
  const now = Date.now();
  return env.DB.prepare(
    `UPDATE quota_reservations
     SET storage_bytes = ?, updated_at = ?, expires_at = ? WHERE id = ?`,
  )
    .bind(bytes, now, now + HOUR_MS, id)
    .run();
}

async function activeReservationTotal(
  userId: string,
): Promise<{ count: number; storage_bytes: number } | null> {
  return env.DB.prepare(
    `SELECT COUNT(*) AS count, COALESCE(SUM(storage_bytes), 0) AS storage_bytes
     FROM quota_reservations WHERE user_id = ? AND expires_at > ?`,
  )
    .bind(userId, Date.now())
    .first<{ count: number; storage_bytes: number }>();
}

async function insertReport(
  reporterId: string,
  targetId: string,
  createdAt: number,
): Promise<void> {
  await env.DB.prepare(
    `INSERT INTO reports
     (id, reporter_user_id, reporter_pseudonym, target_type, target_id, reason,
      details, status, created_at, updated_at, retain_until)
     VALUES (?, ?, 'quota-test', 'user', ?, 'spam', '', 'open', ?, ?, ?)`,
  )
    .bind(
      crypto.randomUUID(),
      reporterId,
      targetId,
      createdAt,
      createdAt,
      createdAt + 2 * 365 * DAY_MS,
    )
    .run();
}

function authenticatedHeaders(token: string): Record<string, string> {
  return {
    "Content-Type": "application/json",
    Cookie: `tomodachi.sid=${token}`,
    Origin: ORIGIN,
  };
}

function randomSlug(): string {
  return crypto.randomUUID().replaceAll("-", "").slice(0, 18);
}

function project(name: string) {
  const timestamp = "2026-07-10T12:00:00.000Z";
  return {
    cells: Array.from({ length: 64 }, (_, index) =>
      index === 0 ? "R1C1" : null,
    ),
    height: 8,
    lockedColors: [],
    meta: { createdAt: timestamp, modifiedAt: timestamp, name },
    usedColors: ["R1C1"],
    version: 1,
    width: 8,
  };
}

async function clearR2(): Promise<void> {
  let cursor: string | undefined;
  do {
    const page = await env.PROJECTS.list({ cursor, limit: 1_000 });
    if (page.objects.length) {
      await env.PROJECTS.delete(page.objects.map((object) => object.key));
    }
    cursor = page.truncated ? page.cursor : undefined;
  } while (cursor);
}
